### ISSUE TITLE
Hello having some issue. 

### ISSUE THREAD

**Issue by cAstraea** [onbalt/servicedeskplus-api#1]
Hello is this still available ? 
I'm getting this error 
Client error: `GET https://sdpondemand.manageengine.com/api/v3/requests` resulted in a `400 Bad Request` response:
{"response_status":{"messages":[{"status_code":4001,"type":"failed","message":"INVALID_TICKET"}],"status":"failed"}}

 Is it because I'm using the ondemand version ? Is this only for on premise service desk instances ? 
I couldn't find out where to generate the TECHNICIAN KEY but service desk sent us these instructions 
https://www.manageengine.com/products/desktop-central/help/configuring_desktop_central/integrating_with_servicedesk_plus_on_demand.html

and I'm trying to use that key

**Comment by onbalt** [comment]
Try to set headers to use received AUTHTOKEN before query by this way:
```php
ServicedeskplusApi::setHeaders([
	'Accept' => 'application/v3+json',
	'Authorization' => 'AUTHTOKEN',
]);
```
